modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "flowing_fluids"
version = "${version}"
displayName = "Flowing Fluids"
authors = "Traben"
description = '''
Gives fluids realistic flowing physics, making them mostly finite.
With various settings for performance, visuals, and gameplay interaction.
'''
logoFile = "assets/flowing_fluids/icon.png"

[[dependencies.flowing_fluids]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowing_fluids]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

