modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "flowing_fluids"
version = "${version}"
displayName = "Flowing Fluids"
authors = "Traben"
description = '''
Gives fluids realistic flowing physics, making them mostly finite.
With various settings for performance, visuals, and gameplay interaction.
'''
logoFile = "assets/flowing_fluids/icon.png"

[[dependencies.flowing_fluids]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowing_fluids]]
modId = "minecraft"
mandatory = true
versionRange = "[${compatible_mc_forge})"
ordering = "NONE"
side = "BOTH"


# this being optional means it will only trigger a warning when
# the mod is present AND has a wrong version
# this warning is needed for the crash triggered by the mixin plugin
[[dependencies.flowing_fluids]]
modId = "create"
mandatory = false
versionRange = "[0.6,)"
ordering = "NONE"
side = "BOTH"
