modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "flowing_fluids"
version = "${version}"
displayName = "FlowingFluids"
authors = "Traben"
description = '''
Gives fluids realistic flowing physics, making them mostly finite.
With various settings for performance, visuals, and gameplay interaction.
'''
logoFile = "assets/flowing_fluids/icon.png"

[[dependencies.flowing_fluids]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowing_fluids]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "flowing_fluids.mixins.json"
