modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "flowing_fluids"
version = "${version}"
displayName = "FlowingFluids"
authors = "Traben"
description = '''
Gives fluids realistic flowing physics, making them mostly finite.
With various settings for performance, visuals, and gameplay interaction.
'''
logoFile = "assets/flowing_fluids/icon.png"

[[dependencies.flowing_fluids]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowing_fluids]]
modId = "minecraft"
type = "required"
versionRange = "[${compatible_mc_forge})"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "flowing_fluids.mixins.json"

[[mixins]]
config = "flowing_fluids_neoforge.mixins.json"

#https://github.com/CaffeineMC/lithium/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric.mod.json-or-neoforge.mods.toml
["lithium:options"]
"mixin.world.chunk_ticking.spread_ice" = false
